version: '3.8'

services:
  api:
    build: .
    image: mof-advisor-api:latest
    container_name: mof-advisor-api-container  # ✅ 添加容器名称
    ports:
      - "8002:8000"
    volumes:
      - ./chroma_db:/app/chroma_db
    env_file:
      - .env
    restart: unless-stopped
